services:
  gtu-auth-service:
    build: .
    container_name: gtu-auth-service
    environment:
      - EUREKA_SERVER_HOST=discovery-server
      - EUREKA_SERVER_PORT=8761
      - SERVER_PORT=0
      - SWAGGER_SERVER_URL=${SWAGGER_SERVER_URL}
      - JWT_SECRET=LbKuwcGpBGZm5tKJ7MmYQa9NfKtJzYMkVwsDsbUwKyA=
    networks:
      - shared_network
networks:
  shared_network:
    external: true