services:
  gtu-auth-service:
    build: .
    container_name: gtu-auth-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/data/reset_tokens
      - SPRING_DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - EUREKA_SERVER_HOST=discovery-server
      - EUREKA_SERVER_PORT=8761
      - SWAGGER_SERVER_URL=${SWAGGER_SERVER_URL}
      - SPRING_RABBITMQ_HOST=${RABBITMQ_HOST}
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - RESET_LINKS_BASE=https://gtu-admin.netlify.app/reset-password
      - SERVER_PORT=0
    volumes:
      - ./data:/data
    networks:
      - shared_network
networks:
  shared_network:
    external: true
